'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class vistoria_forms extends Model {
   
    
    static associate(models) {
    
    }
  }
  vistoria_forms.init({
    Solicitante: DataTypes.TEXT,
    Data_de_realização: DataTypes.TEXT,
    Marca_Modelo: DataTypes.TEXT,
    Ano_fabricação: DataTypes.TEXT,
    Cor: DataTypes.TEXT,
    Combustível: DataTypes.TEXT,
    Placa: DataTypes.TEXT,
    Renavam: DataTypes.TEXT,
    Chassi: DataTypes.TEXT,
    N_Motor: DataTypes.TEXT,
    KM_Hôdometro: DataTypes.TEXT,
    Restrições: DataTypes.TEXT,
    Visão_Geral: DataTypes.TEXT,
    Placas_dianteira_e_traseira: DataTypes.TEXT,
    Etiqueta_ETA_cofre_do_motor: DataTypes.TEXT,
    Etiqueta_batente_de_porta: DataTypes.TEXT,
    Etiqueta_ETA_piso_assoalho_: DataTypes.TEXT,
    Numeração_chassi: DataTypes.TEXT,
    Numeração_motor: DataTypes.TEXT,
    Cintos_de_segurança_dianteiros_LE_LD: DataTypes.TEXT,
    Cintos_de_segurança_traseiros_LE_CENTR_LD: DataTypes.TEXT,
    Vidro_dianteiro_para_brisa: DataTypes.TEXT,
    Vidro_dianteiro_porta_esq_motorista: DataTypes.TEXT,
    Vidro_dianteiro_porta_dir_passageiro: DataTypes.TEXT,
    Vidro_traseiro_porta_esq: DataTypes.TEXT,
    Vidro_traseiro_porta_dir: DataTypes.TEXT,
    Vidros_elétricos_funcionamento: DataTypes.TEXT,
    Vidros_auxiliares_lado_esq: DataTypes.TEXT,
    Vidros_auxiliares_lado_dir: DataTypes.TEXT,
    Vidro_traseiro: DataTypes.TEXT,
    Desembaçador_linhas: DataTypes.TEXT,
    Espelhos_retrovisores_LD_LE: DataTypes.TEXT,
    Espelhos_retrovisores_funcionamento: DataTypes.TEXT,
    Farois_estado_geral_LD_LE: DataTypes.TEXT,
    Farois_originalidade_LD_LE: DataTypes.TEXT,
    Lanternas_originalidade_LD_LE: DataTypes.TEXT,
    Lanternas_estado_geral_LD_LE: DataTypes.TEXT,
    Iluminação_farol_LD_LE: DataTypes.TEXT,
    Iluminação_lanternas_LD_LE: DataTypes.TEXT,
    Iluminação_teto_cabine_parte_anterior: DataTypes.TEXT,
    Iluminação_teto_cabine_parte_posterior: DataTypes.TEXT,
    Iluminação_individual_para_sol_LD_LE: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_PARTE_FRONTAL: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_PARTE_TRASEIRA: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_LATERAL_ESQ: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_LATERAL_DIR: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_TETO: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_PAINEL_FRONTAL: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_COFRE_MOTOR_e_PAREDE_CORTA_FOGO: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_PAINEL_TRASEIRO: DataTypes.TEXT,
    Possui_avaria_dano_estrutural_ASSOALHO_MALA_e_CAIXA_DE_ESTEPE: DataTypes.TEXT,
    Possui_avarias_dano_ESTRUTURA_INFERIOR: DataTypes.TEXT,
    Possui_avaria_dano_CAIXA_DE_AR_ESQ: DataTypes.TEXT,
    Possui_avaria_dano_CAIXA_DE_AR_DIR: DataTypes.TEXT,
    Possui_avaria_dano_PARACHOQUE_DIANTEIRO: DataTypes.TEXT,
    Possui_avaria_dano_PARACHOQUE_TRASEIRO: DataTypes.TEXT,
    Grades: DataTypes.TEXT,
    Coluna_dianteira_LADO_ESQ: DataTypes.TEXT,
    Coluna_dianteira_LADO_DIR: DataTypes.TEXT,
    Coluna_central_LADO_ESQ: DataTypes.TEXT,
    Coluna_central_LADO_DIR: DataTypes.TEXT,
    Coluna_traseira_LADO_ESQ: DataTypes.TEXT,
    Coluna_traseira_LADO_DIR: DataTypes.TEXT,
    Longarina_dianteira_LADO_ESQ: DataTypes.TEXT,
    Longarina_dianteira_LADO_DIR: DataTypes.TEXT,
    Longarina_Traseira_LADO_ESQ: DataTypes.TEXT,
    Longarina_Traseira_LADO_DIR: DataTypes.TEXT,
    Caixas_de_rodas_dianteira: DataTypes.TEXT,
    Caixas_de_rodas_traseira: DataTypes.TEXT,
    Para_choque_dianteiro: DataTypes.TEXT,
    Capô: DataTypes.TEXT,
    Para_lamas_lado_esq: DataTypes.TEXT,
    Para_lamas_lado_dir: DataTypes.TEXT,
    Porta_motorista_lado_esq: DataTypes.TEXT,
    Porta_passageiro_lado_dir: DataTypes.TEXT,
    Porta_traseira_lado_esq: DataTypes.TEXT,
    Porta_traseira_lado_dir: DataTypes.TEXT,
    Lateral_lado_esq: DataTypes.TEXT,
    Lateral_lado_dir: DataTypes.TEXT,
    Teto: DataTypes.TEXT,
    Porta_malas: DataTypes.TEXT,
    Para_choques_traseiro: DataTypes.TEXT,
    Sinais_de_vazamento_por_juntas: DataTypes.TEXT,
    Som_do_motor_funcionando: DataTypes.TEXT,
    Partida_do_motor: DataTypes.TEXT,
    Nível_óleo_do_motor: DataTypes.TEXT,
    Escapamento: DataTypes.TEXT,
    Bateria: DataTypes.TEXT,
    Trocas_de_marcha_com_veículo_parado: DataTypes.TEXT,
    Trocas_de_marcha_com_veículo_em_movimento: DataTypes.TEXT,
    Homocinética: DataTypes.TEXT,
    Funcionamento: DataTypes.TEXT,
    Folgas_e_estalos: DataTypes.TEXT,
    Nível_do_óleo: DataTypes.TEXT,
    Compresor_e_núcleo_funcionamento: DataTypes.TEXT,
    Resfriamento: DataTypes.TEXT,
    Ar_quente: DataTypes.TEXT,
    Difusores_de_ar: DataTypes.TEXT,
    Teto_solar_vidro: DataTypes.TEXT,
    Teto_solar_funcionamento: DataTypes.TEXT,
    Trava_elétrica_funcionamento: DataTypes.TEXT,
    Buzina: DataTypes.TEXT,
    Tomada_12v: DataTypes.TEXT,
    Volante_tabeliê: DataTypes.TEXT,
    Console_central_e_porta_objetos: DataTypes.TEXT,
    Luzes_internas: DataTypes.TEXT,
    Luzes_no_painel: DataTypes.TEXT,
    Bancos_tecido_couro: DataTypes.TEXT,
    Bancos_trilhos: DataTypes.TEXT,
    Bancos_regulagem_ajuste_de_posição: DataTypes.TEXT,
    Forros_de_portas: DataTypes.TEXT,
    Borrachas_de_vedação_das_portas: DataTypes.TEXT,
    Forros_de_teto: DataTypes.TEXT,
    Tapetes: DataTypes.TEXT,
    Carpete: DataTypes.TEXT,
    Medida: DataTypes.TEXT,
    Data_dos_pneus_DOT: DataTypes.TEXT,
    Condição_estado_atual: DataTypes.TEXT,
    Manuais_de_fábrica: DataTypes.TEXT,
    Chave_reserva: DataTypes.TEXT,
    NF_de_compra: DataTypes.TEXT,
    Macaco_chave_de_roda_triângulo: DataTypes.TEXT,
    Revisões_em_concessionária: DataTypes.TEXT
  }, {
    sequelize,
    modelName: 'vistoria_forms',
  });
  return vistoria_forms;
};